workflows:
  mobile-codemagic:
    name: Build Android APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.22.0
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
